version: '3'
services:
  docker-bash-api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    

  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
